# Oefeningen inlabru

Een aantal zaken worden overgenomen van workshop 1, met het doel om dit nu met `inlabru` te modelleren.

### fit fixed effect model

Probleem met factoren:

```{r}
I1 <- bru(Response ~ Type + Soiltexture + HYear,
           data = lg3data,
           family = "gaussian") # gaussian is the default!
```

Aanpassing voor factoren: we maken extra dummy-variabelen aan:

```{r}
lg3data <- 
    lg3data %>% 
    model.matrix(~Type + Soiltexture, .) %>% 
    as.data.frame %>% 
    select(-`(Intercept)`) %>% 
    bind_cols(lg3data, .)
```


```{r}
# lg3data %>% str
lg3data_typestring <-
    lg3data %>% 
    select(matches("Type.+")) %>% 
    colnames %>% 
    str_c(collapse = " + ")
lg3data_soilstring <-
    lg3data %>% 
    select(matches("Soiltexture.+")) %>% 
    colnames %>% 
    str_c(collapse = " + ")
myformula <- 
    str_c("Response ~ ",
          lg3data_typestring,
          " + ",
          lg3data_soilstring,
          " + HYear") %>% 
    as.formula
```

Noot: het model doet er lang over om te fitten, in vergelijking met INLA.

```{r}
Ibru1 <- bru(myformula,
           data = lg3data,
           family = "gaussian") # gaussian is the default!
```

```{r}
Ibru1 %>% summary
```


```{r}
Ibru1 %>% names
```

```{r}
Ibru1 %>% 
    names %>% 
    .[grep("summary", .)]
```


```{r}
Ibru1$summary.fixed
```


```{r}
Ibru1$summary.hyperpar
```

```{r}
Ibru1$marginals.fixed$Type2130_hd %>% plot
```

```{r}
Ibru1 %>% plot("Type2130_hd")
```


```{r}
Ibru1 %>% plot("HYear")
```





